---
# you can select a specific port on the node and route traffic in that way
# make sure you use the same labels that you have on 1-deployemnt.yaml file to select Pods
---
apiVersion: v1
kind: Service
metadata:
  name: python-node-port
  namespace: dev
spec:
  type: NodePort
  selector:
    app: python-server
  ports:
  - port: 80
    targetPort: http
    nodePort: 30001 # range 30000-32767
