---
# using service type LoadBalancer is much more common rather than opening up a port on a Node
# but you need to make sure that the cloud provider where you deploy your K8s support it 
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer-for-python-server
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: python-server
  ports:
    - port: 80
      targetPort: http